// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdEiYHNGWVLVmq6xSxnMkKpkKYCO28g1E',
    appId: '1:345315404020:web:c12654e7b74baeb12516a1',
    messagingSenderId: '345315404020',
    projectId: 'hosipital-management-340f8',
    authDomain: 'hosipital-management-340f8.firebaseapp.com',
    storageBucket: 'hosipital-management-340f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNKX6C8Q0u2vOMg5ReEJ99dZRwUChCwU',
    appId: '1:345315404020:android:3a1c145a46a5b49c2516a1',
    messagingSenderId: '345315404020',
    projectId: 'hosipital-management-340f8',
    storageBucket: 'hosipital-management-340f8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdEiYHNGWVLVmq6xSxnMkKpkKYCO28g1E',
    appId: '1:345315404020:web:e3c876f4691c67a22516a1',
    messagingSenderId: '345315404020',
    projectId: 'hosipital-management-340f8',
    authDomain: 'hosipital-management-340f8.firebaseapp.com',
    storageBucket: 'hosipital-management-340f8.appspot.com',
  );

}